#!/usr/bin/env bash
#transfers a file from our client to a server.
PATH=$1
IP=$2
USER=$3
PRIVATEKEY=$4
if (("$#" < 4))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$PRIVATEKEY" "$PATH" "$USER@$IP":~/
fi
