#!/usr/bin/env bash
#transfers a file from our client to a server.

if ["$#" -lt 4]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
PRIVATEKEY=$4
USER=$3
IP=$2
PATH_FILE=$1
    scp -o StrictHostKeyChecking=no -i "$PRIVATEKEY" "$PATH_FILE" "$USER@$IP":~
fi
