#!/usr/bin/env bash
# redirect page

sudo apt-get update
sudo apt-get -y install nginx
# Enable PORT 80
sudo ufw allow 'Nginx HTTP'
# Create the file and add string
echo "Holberton School" > /var/www/html/index.html
# redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
