#!/usr/bin/env bash
# Set custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
# Enable PORT 80
sudo ufw allow 'Nginx HTTP'
# Create the file and add string
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "Holberton School" > /var/www/html/index.html
# redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# redirection
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
