#!/usr/bin/env bash
# Create a file and try to kill it
echo $$ > /var/run/holbertonscript.pid
while :
do
	trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
