#!/usr/bin/env bash
n=0
while (( n <= 9 ))
do
    if ((n == 3))
    then
        echo "bad luck"
    elif (( n == 7 ))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    n=$((n+1))
done
