#!/usr/bin/env bash
#  Write a Bash script that loops from 1 to 10.
n=1
while (( n <= 10 ))
do
    if ((n == 4))
    then
        echo "bad luck"
    elif (( n == 8 ))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    (( n++ ))
done
