#!/usr/bin/env bash
#clock in bash
seconds=1
hour=0
while ((hour <= 12 ))
do
    echo "Hour: $hour"
    seconds=1
    while(( seconds < 60))
    do
        echo $seconds
        seconds=$((seconds+1))
    done
    hour=$((hour+1))
done
